#ifndef PREDICTOROUTPUTTYPE_H
#define PREDICTOROUTPUTTYPE_H


enum class PredictorOutputType
{
    SERIES,
    PREDICTION,
    BASELINE,
    SEASONAL,
    MA,
    MA2DIFF,
    MA2DIFF_NO_SEASONAL,
    RECONSTRUCTION,
    RECONSTRUCTION_PRED,
    RECONSTRUCTION_PRED_BASELINE
};

#endif // PREDICTOROUTPUTTYPE_H
