#ifndef SIMULATORTYPE_H_INCLUDED
#define SIMULATORTYPE_H_INCLUDED

enum class SimulatorType
{
    SIMUL_MT,
    SIMUL_BET,
    SIMUL_TEFO,
    SIMUL_MAX_PROFIT,
    SIMUL_DISCOVERY,
    SIMUL_IN_SAMPLE,
    SIMUL_STANDARD
};

#endif // SIMULATORTYPE_H_INCLUDED
