name: ci/gh-actions/cli

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

# The below variables reduce repetitions across similar targets
env:
  REMOVE_BUNDLED_BOOST : rm -rf /usr/local/share/boost
  APT_SET_CONF: |
        echo "Acquire::Retries       \"3\";"   | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::http::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::ftp::Timeout  \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      CCACHE_TEMPDIR: C:\Users\runneradmin\.ccache-temp
      CCACHE_DIR: C:\Users\runneradmin\.ccache
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    # Volatile cache
    - name: ccache
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key:          ccache03-${{ runner.os }}-build-${{ github.sha }}
        restore-keys: ccache03-${{ runner.os }}-build-
    # Less volatile cache
    - name: data cache
      uses: actions/cache@v2
      with:
        path: build/data/data/txt
        key:          data-${{ hashFiles('build/data/data/txt/**/*') }}
        restore-keys: data-${{ hashFiles('build/data/data/txt/**/*') }}
    - uses: eine/setup-msys2@v2
      with:
        update: true
        install: mingw-w64-x86_64-toolchain make mingw-w64-x86_64-cmake mingw-w64-x86_64-ccache mingw-w64-x86_64-gnuplot mingw-w64-x86_64-eigen3 mingw-w64-x86_64-unittest-cpp mingw-w64-x86_64-boost mingw-w64-x86_64-gsl mingw-w64-x86_64-wxWidgets mingw-w64-x86_64-winpthreads-git git # mingw-w64-x86_64-openssl mingw-w64-x86_64-zeromq
    - name: prepare environment
      run: util/prep-env.sh
# TODO: Use python later
    - name: install dependencies
      run: util/deps-pull.sh
    - name: build & install the unmanaged dependencies
      run: util/deps-build.sh
    - name: build
      run: ./ci-default --unity
    - name: run demo
      run: ./ci-default --unity --run-demo       
    - name: prep bin
      run: |
        ls /mingw64/bin
        cp /mingw64/bin/libwinpthread-1.dll D:/a/tsqsim/tsqsim/build/default-static-release/bin
        cp /mingw64/bin/libstdc++-6.dll D:/a/tsqsim/tsqsim/build/default-static-release/bin
        cp /mingw64/bin/libgcc_s_seh-1.dll D:/a/tsqsim/tsqsim/build/default-static-release/bin
        cp /mingw64/bin/libboost_program_options-mt.dll D:/a/tsqsim/tsqsim/build/default-static-release/bin
        cp /mingw64/bin/libboost_serialization-mt.dll D:/a/tsqsim/tsqsim/build/default-static-release/bin
        cp /mingw64/bin/libboost_system-mt.dll D:/a/tsqsim/tsqsim/build/default-static-release/bin
        cp /mingw64/bin/libboost_filesystem-mt.dll D:/a/tsqsim/tsqsim/build/default-static-release/bin
        cp /mingw64/bin/libboost_date_time-mt.dll D:/a/tsqsim/tsqsim/build/default-static-release/bin
        cp /mingw64/bin/libboost_iostreams-mt.dll D:/a/tsqsim/tsqsim/build/default-static-release/bin
        cp /mingw64/bin/wxbase30u_gcc_custom.dll D:/a/tsqsim/tsqsim/build/default-static-release/bin
        cp /mingw64/bin/wxmsw30u_gcc_custom.dll D:/a/tsqsim/tsqsim/build/default-static-release/bin
    - uses: actions/upload-artifact@v2
      with:
        name: tsqsim-Windows
        path: |
          D:/a/tsqsim/tsqsim/build/default-static-release/bin/*
          !D:/a/tsqsim/tsqsim/build/default-static-release/bin/lib/*
          !D:/a/tsqsim/tsqsim/build/default-static-release/bin/data/data/bin/*
          !D:/a/tsqsim/tsqsim/build/default-static-release/bin/cfg/configTxt.txt


