name: ci/gh-actions/cli

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

# The below variables reduce repetitions across similar targets
env:
  REMOVE_BUNDLED_BOOST : rm -rf /usr/local/share/boost
  APT_SET_CONF: |
        echo "Acquire::Retries       \"3\";"   | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::http::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::ftp::Timeout  \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom

jobs:
  build-ubuntu:
    runs-on: ${{ matrix.os }}
    env:
      CCACHE_TEMPDIR: /tmp/.ccache-temp
    strategy:
      fail-fast: false
#      max-parallel: 1 # Single threaded for now, because the jobs overwrite each other's data/bin/* files?
      matrix:
        os: [ubuntu-latest] #, ubuntu-18.04] # TODO: Consider(!) supporting the previous version.
        compiler: [gcc, clang]
        linkage: ["", --shared, --lto]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    # Volatile cache
    - name: ccache
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key:          ccache03-${{ runner.os }}-${{ matrix.os }}-${{ matrix.compiler }}-${{ matrix.linkage }}-build-${{ github.sha }}
        restore-keys: ccache03-${{ runner.os }}-${{ matrix.os }}-${{ matrix.compiler }}-${{ matrix.linkage }}-build-
    # Less volatile cache
    - name: data cache
      uses: actions/cache@v2
      with:
        path: build/data/data/txt
        key:          data-${{ hashFiles('build/data/data/txt/**/*') }}
        restore-keys: data-${{ hashFiles('build/data/data/txt/**/*') }}
#    - name: deps cache
#      uses: actions/cache@v2
#      with:
#        path: build/deps/dload
#        key:          deps-${{ hashFiles('build/deps/dload/*') }}
#        restore-keys: deps-${{ hashFiles('build/deps/dload/*') }}
    - name: prepare environment
      run: util/prep-env.sh
    - name: set apt conf
      run: ${{env.APT_SET_CONF}}
    - name: install dependencies
      run: util/deps-pull.sh
    - name: build & install the unmanaged dependencies
      run: util/deps-build.sh
    - name: build
      run: ./ci-default --compiler ${{ matrix.compiler }} ${{ matrix.linkage }} --unity --build-qt
    - name: run demo
      run: ./ci-default --compiler ${{ matrix.compiler }} ${{ matrix.linkage }} --unity --build-qt --run-demo
# It doesn't make sense for now, since we're not linking Boost statically yet.
#    - uses: actions/upload-artifact@v2
#      if: ${{ matrix.compiler == 'gcc' && matrix.linkage == '--lto' }}
#      with:
#        name: tsqsim-${{ matrix.os }}
#        path: /home/runner/work/tsqsim/tsqsim/build/${{ matrix.compiler }}-static-release/bin/*

# TODO: todos sorted by priority*realism:
# TODO: All the unmaintained denendencies should have their own CMakeLists.txt file (URT. Others?) and the util/deps-build.sh should not be used, if possible.
# TODO: All the testing should be done in a separate job, AFTER building and downloading resources, in order to use caches better (short and easy. Needs to have the build scripts restructured - separate building and testing)

  build-macos:
    runs-on: ${{ matrix.os }}
    env:
      CCACHE_TEMPDIR: /tmp/.ccache-temp
    strategy:
      fail-fast: false
      matrix:
        #os: [macOS-latest, macOS-11]    # prev
        #os: [macOS-latest, macOS-10.15] # future 
        os: [macOS-10.15, macOS-11]      # transitionary
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    # Volatile cache
    - name: ccache
      uses: actions/cache@v2
      with:
        path: /Users/runner/Library/Caches/ccache
        key:          ccache03-${{ runner.os }}-${{ matrix.os }}-build-${{ github.sha }}
        restore-keys: ccache03-${{ runner.os }}-${{ matrix.os }}-build-
    # Less volatile cache
    - name: data cache
      uses: actions/cache@v2
      with:
        path: build/data/data/txt
        key:          data-${{ hashFiles('build/data/data/txt/**/*') }}
        restore-keys: data-${{ hashFiles('build/data/data/txt/**/*') }}
    - name: prepare environment
      run: util/prep-env.sh
    - name: install dependencies
      run: util/deps-pull.sh
    - name: build & install the unmanaged dependencies
      run: util/deps-build.sh
    - name: build
      run: ./ci-default --unity --lto
    - name: run demo
      run: ./ci-default --unity --lto --run-demo
    - uses: actions/upload-artifact@v2
      with:
        name: tsqsim-${{ matrix.os }}
        path: |
          /Users/runner/work/tsqsim/tsqsim/build/default-static-release/bin/*
          !/Users/runner/work/tsqsim/tsqsim/build/default-static-release/bin/lib/*
          !/Users/runner/work/tsqsim/tsqsim/build/default-static-release/bin/data/data/bin/*

  build-windows:
    runs-on: windows-latest
    env:
      CCACHE_TEMPDIR: C:\Users\runneradmin\.ccache-temp
      CCACHE_DIR: C:\Users\runneradmin\.ccache
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    # Volatile cache
    - name: ccache
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key:          ccache03-${{ runner.os }}-build-${{ github.sha }}
        restore-keys: ccache03-${{ runner.os }}-build-
    # Less volatile cache
    - name: data cache
      uses: actions/cache@v2
      with:
        path: build/data/data/txt
        key:          data-${{ hashFiles('build/data/data/txt/**/*') }}
        restore-keys: data-${{ hashFiles('build/data/data/txt/**/*') }}
    - uses: eine/setup-msys2@v2
      with:
        update: true
        install: mingw-w64-x86_64-toolchain make mingw-w64-x86_64-cmake mingw-w64-x86_64-ccache mingw-w64-x86_64-gnuplot mingw-w64-x86_64-eigen3 mingw-w64-x86_64-unittest-cpp mingw-w64-x86_64-boost mingw-w64-x86_64-gsl mingw-w64-x86_64-wxWidgets mingw-w64-x86_64-winpthreads-git git # mingw-w64-x86_64-openssl mingw-w64-x86_64-zeromq
    - name: prepare environment
      run: util/prep-env.sh
# TODO: Use python later
    - name: install dependencies
      run: util/deps-pull.sh
    - name: build & install the unmanaged dependencies
      run: util/deps-build.sh
    - name: build
      run: ./ci-default --unity
    - name: run demo
      run: ./ci-default --unity --run-demo       
    - name: prep bin
      run: |
        ls /mingw64/bin
        cp /mingw64/bin/libwinpthread-1.dll D:/a/tsqsim/tsqsim/build/default-static-release/bin
        cp /mingw64/bin/libstdc++-6.dll D:/a/tsqsim/tsqsim/build/default-static-release/bin
        cp /mingw64/bin/libgcc_s_seh-1.dll D:/a/tsqsim/tsqsim/build/default-static-release/bin
        cp /mingw64/bin/libboost_program_options-mt.dll D:/a/tsqsim/tsqsim/build/default-static-release/bin
        cp /mingw64/bin/libboost_serialization-mt.dll D:/a/tsqsim/tsqsim/build/default-static-release/bin
        cp /mingw64/bin/libboost_system-mt.dll D:/a/tsqsim/tsqsim/build/default-static-release/bin
        cp /mingw64/bin/libboost_filesystem-mt.dll D:/a/tsqsim/tsqsim/build/default-static-release/bin
        cp /mingw64/bin/libboost_date_time-mt.dll D:/a/tsqsim/tsqsim/build/default-static-release/bin
        cp /mingw64/bin/libboost_iostreams-mt.dll D:/a/tsqsim/tsqsim/build/default-static-release/bin
        cp /mingw64/bin/wxbase30u_gcc_custom.dll D:/a/tsqsim/tsqsim/build/default-static-release/bin
        cp /mingw64/bin/wxmsw30u_core_gcc_custom.dll D:/a/tsqsim/tsqsim/build/default-static-release/bin
        cp /mingw64/bin/libjpeg-8.dll D:/a/tsqsim/tsqsim/build/default-static-release/bin
        cp /mingw64/bin/libpng16-16.dll D:/a/tsqsim/tsqsim/build/default-static-release/bin
        cp /mingw64/bin/libbz2-1.dll D:/a/tsqsim/tsqsim/build/default-static-release/bin
        cp /mingw64/bin/liblzma-5.dll D:/a/tsqsim/tsqsim/build/default-static-release/bin
        cp /mingw64/bin/libzstd.dll D:/a/tsqsim/tsqsim/build/default-static-release/bin
        cp /mingw64/bin/libtiff-5.dll D:/a/tsqsim/tsqsim/build/default-static-release/bin
    - uses: actions/upload-artifact@v2
      with:
        name: tsqsim-Windows
        path: |
          D:/a/tsqsim/tsqsim/build/default-static-release/bin/*
          !D:/a/tsqsim/tsqsim/build/default-static-release/bin/lib/*
          !D:/a/tsqsim/tsqsim/build/default-static-release/bin/data/data/bin/*
          !D:/a/tsqsim/tsqsim/build/default-static-release/bin/cfg/configTxt.txt


